# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 174.129.186.149
  become: yes

  tasks:

- name: Call Roles
  hosts: 174.129.186.149
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
